In [1]:
from dbanalysis.classes import time_tabler_refac as time_tabler

In [2]:
import datetime
dt= datetime.datetime.now()

In [4]:
t = time_tabler.time_tabler()

In [8]:
m=t.get_dep_times_five_days('1',dt)

In [10]:
m[0]['matrix']

     actualtime_arr_from  day  busID  month  weekend  variation  hour
0                  61200    5     39      8     True          0    17
1                  63600    5     40      8     True          0    17
2                  62400    5     41      8     True          0    17
3                  32400    5     42      8     True          0     9
4                  34200    5     43      8     True          0     9
5                  36000    5     44      8     True          0    10
6                  39600    5     45      8     True          0    11
7                  37800    5     46      8     True          0    10
8                  41400    5     47      8     True          0    11
9                  28800    5     48      8     True          0     8
10                 30600    5     49      8     True          0     8
11                 43200    5     50      8     True          0    12
12                 50400    5     51      8     True          0    14
13                 46800    5     52      8     True          0    13
14                 45600    5     53      8     True          0    12
15                 52800    5     54      8     True          0    14
16                 49200    5     55      8     True          0    13
17                 48000    5     56      8     True          0    13
18                 44400    5     57      8     True          0    12
19                 51600    5     58      8     True          0    14
20                 57600    5     59      8     True          0    16
21                 54000    5     60      8     True          0    15
22                 60000    5     61      8     True          0    16
23                 56400    5     62      8     True          0    15
24                 55200    5     63      8     True          0    15
25                 58800    5     64      8     True          0    16
26                 64800    5     65      8     True          0    18
27                 66600    5     66      8     True          0    18
28                 72000    5     67      8     True          0    20
29                 68400    5     68      8     True          0    19
..                   ...  ...    ...    ...      ...        ...   ...
194                37200    2      9      8    False          0    10
195                38400    2     10      8    False          0    10
196                39600    2     11      8    False          0    11
197                36000    2     12      8    False          0    10
198                42000    2     13      8    False          0    11
199                40800    2     14      8    False          0    11
200                46800    2     15      8    False          0    13
201                48000    2     16      8    False          0    13
202                44400    2     17      8    False          0    12
203                49200    2     18      8    False          0    13
204                45600    2     19      8    False          0    12
205                51600    2     20      8    False          0    14
206                50400    2     21      8    False          0    14
207                43200    2     22      8    False          0    12
208                52800    2     23      8    False          0    14
209                73800    2     24      8    False          0    20
210                68400    2     25      8    False          0    19
211                70200    2     26      8    False          0    19
212                72000    2     27      8    False          0    20
213                81000    2     28      8    False          0    22
214                75600    2     29      8    False          0    21
215                82800    2     30      8    False          0    23
216                77400    2     31      8    False          0    21
217                79200    2     32      8    False          0    22
218                34800    2     33      8    False          0     9
219                32400    2     34      8    False          0     9
220                33600    2     35      8    False          0     9
221                63600    2     36      8    False          0    17
222                61200    2     37      8    False          0    17
223                62400    2     38      8    False          0    17

[224 rows x 7 columns]